apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-noticias-deployment
spec:
  template:
    metadata:
      name: bd-noticias
      labels:
        app: bd-noticias
    spec:
      containers:
        - name: bd-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: bd-configmap
  selector:
    matchLabels:
      app: bd-noticias