apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      volumeMounts:
        - mountPath: /volume-dentro-container
          name: primeiro-volume
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-1